### ISSUE TITLE
Are you openly developing this?

### ISSUE THREAD

**Issue by jgladch** [astrolin/ephemeris-api#1]
Looks like a very promising project, but no updates in 2 years.

**Comment by orlin** [comment]
Yes, I was basically struggling to find the time.  2017 got to be a very busy year.  Then my astrology teacher, Robert Schmidt, suddenly passed away, and I went through a period of not knowing what I want to do with astrology.

Lately I have renewed my plans and am about to continue developing it in public, at least as far as `ephemeris` + `ephemeris-api` goes.  Other things will also be built, which may or may not be opensource, though it's essential for the ephemeris and this `http` interface to remain open.

Thanks for your interest and patience.  More to come.
